### ISSUE TITLE
Memory leak in SimpleMortyApplication class

### ISSUE THREAD

**Issue by itsusmon** [the-android-factory/Simple-Morty#1]
I was gonna do a code review then I've seen the Application class and I changed my mind.

I think you don't have to save context statically. It will be reason to happening memory leak. You have to use DI or something else

**Comment by the-android-factory** [comment]
Hey! Yeah the Application class context being static is just a helpful tool throughout the app for ease-of-use. DI would definitely be a better approach, but I did not include that in this project. Check out my [newest season](https://youtube.com/playlist?list=PLLgF5xrxeQQ2qeszlLJTuL9ZO4bSpngQr) where we use Hilt from the beginning and will use it as we build out other features in the future :)

**Comment by itsusmon** [comment]
Oh. Thanks. I've subscribed :)
